In [2]:
import cv2
#import numpy as np
#import matplotlib.pyplot as plt
img=  cv2.imread("image1.jpg",cv2.IMREAD_GRAYSCALE)#GRAYSCALE=0
print(img)
img=cv2.resize(img,(500,500))
cv2.imshow('image',img)
k=cv2.waitKey(0)
if k==27:
  cv2.destroyAllWindows()
elif k==ord('s'):
  cv2.imwrite('grayscale.jpg', img)
  cv2.destroyAllWindows()


[[85 87 88 ... 26 26 26]
 [85 86 86 ... 26 26 26]
 [85 84 84 ... 26 26 26]
 ...
 [25 26 26 ... 27 28 28]
 [26 26 25 ... 27 28 28]
 [26 25 25 ... 27 28 28]]
